apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app
spec:
  volumes:
  - name: nginx-config-defalut
    configMap:
      name: nginx-config
  containers:
    - image: nginx:alpine
      name: nginx
      ports:
      - containerPort: 80
      volumeMounts:
        - name: nginx-config-defalut
          mountPath: /etc/nginx/conf.d/