apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: app
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;

      return 302 https://google.com;
    }